app_name: "OveRune Forging"
bundle_id: "com.ashleyswear.runeforge"
icon_path: "Icon.png"
team_id: "95CL3CTYVJ"
app_version: "2.0.0"
build_number: "1"
podfile_path: "scripts/Podfile"
nse_swift_path: "scripts/NotificationService.swift"
nse_plist_path: ""
